Feat/runtime check
subscan-explorer/network-runtime-check pull request #1
Opened 2022-06-16 01:15 UTC by cuckooemm

link https://github.com/subscan-explorer/subscan/issues/1755

2022-06-16 01:57 UTC, freehere107 requested changes

2022-06-16 01:57 UTC, freehere107 commented on README.md
> +#### 展示网络支持的所有 pallet
改成英文

2022-06-16 01:57 UTC, freehere107 commented on Dockerfile
> +ENV GOPROXY https://goproxy.cn,direct
GOPROXY 去掉，使用这个项目的人很可能不在国内

2022-06-16 01:57 UTC, freehere107 commented on README.md
> +$ docker run --name runtime-check --rm -e SUBSCAN_API_KEY={{token}} runtime-check bin/runtime-check -pallet=System,Babe
加1个输出后的结果

2022-06-16 01:57 UTC, freehere107 commented on go.mod
> +module network-runtime-check
改成全路径 ``github.com/subscan-explorer/network-runtime-check``

2022-06-16 01:57 UTC, freehere107 commented on internal/match/pallet.go
> +	concurrency := 1
默认没有 ``API KEY`` 是 2 QPS

2022-06-16 01:57 UTC, freehere107 commented on internal/match/pallet.go
> +		concurrency = 5
我建议这里不要写死，https://support.subscan.io/#rate-limiting header会返回 ``rate-limit``

2022-06-16 01:57 UTC, freehere107 commented on internal/match/pallet.go
> +	for i := 0; i < concurrency; i++ {
这里的逻辑有些奇怪，不应该循环 **networkNode**  然后往 **palletCh chan** 写就好了么

2022-06-16 01:57 UTC, freehere107 commented on internal/match/pallet.go
> +		if _, ok := modelSet[model]; ok {
用map需要大小写完全匹配，不太好用

2022-06-16 01:57 UTC, freehere107 commented on internal/match/pallet.go
> +			result = append(result, model)
我刚才试了下网络中间输出没有隔开
```
┌──────────┬──────────────────┐
│ Network  │ Pallet           │
├──────────┼──────────────────┤
│ polkadot │                  │
│ kusama   │ context canceled │
└──────────┴──────────────────┘
```

2022-06-16 01:57 UTC, freehere107 commented on internal/rumtime/list.go
> +			_, _ = io.Copy(ioutil.Discard, rsp.Body)
这行没有看懂

2022-06-16 01:57 UTC, freehere107 commented on internal/match/pallet.go
> +	"picasso", "pioneer", "polkadex", "polymesh", "polymesh-testnet", "plasm", "quartz", "reef",
**plasm** 删掉

2022-06-16 01:57 UTC, cuckooemm commented on Dockerfile
> +ENV GOPROXY https://goproxy.cn,direct
ok

2022-06-16 02:02 UTC, cuckooemm commented on internal/match/pallet.go
> +		if _, ok := modelSet[model]; ok {
如果 pallet 不区分大小写的话
可以 `strings.ToLower()` 处理

2022-06-16 02:29 UTC, cuckooemm commented on internal/rumtime/list.go
> +			_, _ = io.Copy(ioutil.Discard, rsp.Body)
这里是对链接读缓冲区进行清空

2022-06-16 02:30 UTC, cuckooemm commented on internal/rumtime/list.go
> +			_, _ = io.Copy(ioutil.Discard, rsp.Body)
`body.Close()` 不会对缓冲区进行情况
导致链接不能复用

2022-06-16 03:58 UTC, cuckooemm commented on internal/match/pallet.go
> +	for i := 0; i < concurrency; i++ {
直接循环存在并发问题，这样写是为了简单
目前通过atomic处理Idx

2022-06-16 05:18 UTC, MittWillson commented on internal/match/pallet.go
> +				if atomic.AddInt64(closeCount, 1) == int64(concurrency) {
可以考虑 waitGroup 代替

2022-06-19 12:48 UTC, freehere107 commented on internal/match/pallet.go
> +				result := matchPallet(ctx, nw, pallet)
这没有控制并发吧？

2022-06-20 09:53 UTC, cuckooemm commented on internal/match/pallet.go
> +				result := matchPallet(ctx, nw, pallet)
> 这没有控制并发吧？

`limitCh <- struct{}{}:` 这里控制并发 
`waitgroup` 是等待所有work退出关闭channel

2022-06-20 09:59 UTC, freehere107 approved these changes

2022-06-20 09:59 UTC, merged